automation:
# Erika är nästan hemma
  - alias: "Erika nästan hemma"
    trigger:
      platform: state
      entity_id: device_tracker.erikasiphone
      from: 'not_home'
      to: 'nastan_hemma'

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ states.device_tracker.isaksiphone.state == "home" }}'

    action:
      - service: notify.ios_isaksiphone
        data:
          message: "Erika är 500 meter hemifrån."
# Isak är nästan hemma
  - alias: "Isak nästan hemma"
    trigger:
      platform: state
      entity_id: device_tracker.isaksiphone
      from: 'not_home'
      to: 'nastan_hemma'

    condition:
      condition: and
      conditions:
        - condition: template
          value_template: '{{ states.device_tracker.erikasiphone.state == "home" }}'

    action:
      - service: notify.ios_erikasiphone
        data:
          message: "Isak är 500 meter hemifrån."
