# This package is to control lighting when I'm watching Apple TV
# If Apple TV is playing close to sunset, TV mode is started (automation 1)
# If Apple TV is paused, a 30 second timer is started (automation 2)
# If Apple TV start playing again within 30 seconds, the timer is cancelled (automation 1)
# If Apple TV is still paused after 30 seconds, lights are turned on again (automation 3)

timer:
  atvpaused:
    duration: '00:00:30'

automation:
  - alias: "Starta TV-läge då Apple TV spelar efter solnedgång"
    trigger:
      platform: state
      entity_id: media_player.apple_tv
      to: 'playing'

    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"

    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.scenepicker
          option: "TV"
      - service: timer.cancel
        entity_id: timer.atvpaused


  - alias: "Starta timer om Apple TV pausar efter solnedgång"
    trigger:
      platform: state
      entity_id: media_player.apple_tv
      from: 'playing'
      to: 'paused'

    condition:
      condition: and
      conditions:
        - condition: sun
          after: sunset
          after_offset: "-01:00:00"

    action:
      service: timer.start
      entity_id: timer.atvpaused

  - alias: "Starta Hemmaläge när timern är slut"
    trigger:
      platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.atvpaused

    action:
      service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Hemma"
