# Timer to turn off coffee brewer if it is still on after 1 hour
# Please also see iOS configuration in main configuration.yaml. Having that configuration here
# triggered a configuration error
# Next up: Add a countdown (1), Turn off if users don't acknowledge the notification.

automation:
# When coffee brewer is started, trigger the countdown
  - alias: "Kaffebryggare av efter 60 minuter"

    trigger:
      platform: state
      entity_id: switch.kitchen_coffeebrewer_switch
      to: 'on'

    action:
      - service: script.turn_on
        entity_id: script.coffeecountdown

# If coffee brewer is manually turned off before countdown ended, stop the countdown
  - alias: "Stop CoffeeCountdown"
    hide_entity: true

    trigger:
      platform: state
      entity_id: switch.kitchen_coffeebrewer_switch
      to: 'off'

    action:
      - service: script.turn_off
        entity_id: script.coffeecountdown
      - service: script.turn_off
        entity_id: script.coffee20minutes

# If iOS User chooses 20 more minutes, run script coffee20minutes
  - alias: "Coffee20Minutes"
    hide_entity: true

    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: COFFEE_20_MINUTES

    action:
      - service: script.turn_on
        entity_id: script.coffee20minutes

# If iOS User chooses to turn off, then turn off
  - alias: "CoffeeTurnOff"
    hide_entity: true

    trigger:
      platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: COFFEE_TURNOFF

    action:
      - service: switch.turn_off
        entity_id: switch.kitchen_coffeebrewer_switch

# Countdown
script:
  coffeecountdown:
    sequence:
      - delay: 01:00:00

      # Notify iOS
      - service: notify.ios_isaksiphone
        data:
          title: "Timer"
          message: "Kaffebryggaren har varit på en timme. Vill du stänga av den?"
          data:
            push:
              category: 'coffeetimer'
      - service: notify.ios_erikasiphone
        data:
          title: "Timer"
          message: "Kaffebryggaren har varit på en timme. Vill du stänga av den?"
          data:
            push:
              category: 'coffeetimer'

  coffee20minutes:
    sequence:
      - delay: 00:20:00

      # Notify iOS
      - service: notify.ios_isaksiphone
        data:
          title: "Timer"
          message: "Kaffebryggaren har varit på i 20 minuter till. Vill du stänga av den?"
          data:
            push:
              category: 'coffeetimer'
      - service: notify.ios_erikasiphone
        data:
          title: "Timer"
          message: "Kaffebryggaren har varit på i 20 minuter till. Vill du stänga av den?"
          data:
            push:
              category: 'coffeetimer'
