# Requirement: config/python_scripts/count_entities_on.py
automation:
  - alias: "Update entities on"
    trigger:
      - platform: state
        entity_id:
          - switch.hall_spegel_switch
          - switch.bedroom_window_switch
          - switch.kitchen_window_switch
          - switch.kitchen_tolomeo_switch
          - switch.kitchen_coffeebrewer_switch
          - switch.livingroom_window_switch
          - light.bedroom_isakbedside_level
          - light.bedroom_erikabedside_level
          - light.kitchen_spotlight_level
          - light.livingroom_cornerlight_level
          - switch.samsung_tv
          - switch.sonos_bedroom
          - switch.sonos_livingroom
      - platform: homeassistant
        event: start
    action:
      - service: python_script.count_entities_on
