# Package for pollen sensor.
# Requirements: pollenkoll.py (see config/custom_components/sensor/pollenkoll.py) as made by https://github.com/JohNan/home-assistant-pollenkoll
sensor:
# Initial HA Sensor to fetch pollen data from pollenkoll.se. What you put in state doesn't matter (as long as you put a pollen type there, as we will interpret data later on)
  - platform: pollenkoll
    sensors:
      - city: Stockholm
        state: Gräs
# Let's get started with template sensors:
  - platform: template
    sensors:
      pollen_al:
        friendly_name: "Al"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Al']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Al'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Al'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_alm:
        friendly_name: "Alm"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Alm']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Alm'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Alm'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_bjork:
        friendly_name: "Björk"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Björk']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Björk'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Björk'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_bok:
        friendly_name: "Bok"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Bok']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Bok'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Bok'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_ek:
        friendly_name: "Ek"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Ek']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Ek'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Ek'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_gras:
        friendly_name: "Gräs"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Gräs']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gräs'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_grabo:
        friendly_name: "Gråbo"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Gråbo']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Gråbo'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_hassel:
        friendly_name: "Hassel"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Hassel']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Hassel'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}
      pollen_salgvide:
        friendly_name: "Sälg / vide"
        value_template: "{{states.sensor.pollenkoll_stockholm.attributes['Sälg / vide']}}"
        entity_picture_template: >
          {% if states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "i.u." %}
            /local/pollenstatus_iu.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "i.h." %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "L" %}
            /local/pollenstatus_ih-l.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "L-M" %}
            /local/pollenstatus_l-m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "M" %}
            /local/pollenstatus_m.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "M-H" %}
            /local/pollenstatus_m-h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "H" %}
            /local/pollenstatus_h.png
          {% elif states.sensor.pollenkoll_stockholm.attributes['Sälg / vide'] == "H+" %}
            /local/pollenstatus_hplus.png
          {% endif %}

# Nice group to show in frontend:
group:
  pollenkoll:
    name: "Pollenrapport"
    entities:
      - sensor.pollen_al
      - sensor.pollen_alm
      - sensor.pollen_bjork
      - sensor.pollen_bok
      - sensor.pollen_ek
      - sensor.pollen_gras
      - sensor.pollen_grabo
      - sensor.pollen_hassel
      - sensor.pollen_salgvide
