# The objective of this package is to create a scene picker in frontend.
# If user picks a scene, that scene should be performed.
# Other automations performing scenes should also go through scene picker so that frontend always shows the correct scene.

###############################################################################
## INPUT SELECT
###############################################################################

# Define dropdown list to pick playlist from
input_select:
  playlistpicker:
    name: "Välj spellista"
    options:
      - "Fredag och rödvin"
      - "Isaks lista"
      - "Julmusik"
      - "Lars Winnerbäck"
      - "Stockholm"
      - "Sweet Soul Sunday"

###############################################################################
## INPUT NUMBER
###############################################################################

# Define input slider to select volume
input_number:
  volumeslider:
    name: "Volym"
    min: 0
    max: 100
    step: 1

###############################################################################
## AUTOMATIONS
###############################################################################

# Play playlist based on which one is picked.
automation:
  - alias: "Kör spellista"
    hide_entity: true

    trigger:
      platform: state
      entity_id: input_select.playlistpicker

    action:
      - service: media_player.select_source
        data_template:
          entity_id: media_player.vardagsrum
          source: >
            {% if is_state("input_select.playlistpicker", "Fredag och rödvin") %}
              "Fredag och rödvin"
            {%-elif is_state("input_select.playlistpicker", "Isaks lista") %}
              "Isak"
            {%-elif is_state("input_select.playlistpicker", "Julmusik") %}
              "JUL MED MAGNUS (och andra kanske)"
            {%-elif is_state("input_select.playlistpicker", "Lars Winnerbäck") %}
              "Lars Winnerbäck"
            {%-elif is_state("input_select.playlistpicker", "Stockholm") %}
              "Stockholm"
            {%-elif is_state("input_select.playlistpicker", "Sweet Soul Sunday") %}
              "Sweet Soul Sunday"
            {% else %}
              none
            {% endif %}

# Set volume based on input slider
  - alias: "Kör volym"
    hide_entity: true

    trigger:
      platform: state
      entity_id: input_number.volumeslider

    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.vardagsrum
          volume_level: '{{ trigger.to_state.state | int }}'

# Set input slider based on changes in volume
  - alias: "Om volym körs ändra input slider"
    hide_entity: true

    trigger:
      platform: state
      entity_id: media_player.volume_level

    service: input_number.set_value
    data:
      entity_id: input_number.volumeslider
      value: 

###############################################################################
## GROUP
###############################################################################
group:
  soundbar:
    name: "Soundbar"
    entities:
      - input_select.playlistpicker
      - input_number.volumeslider
