# Lamps on at sunset and someone is home
- alias: "Automatisk belysning vid solnedgång"
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: switch.hall_light_spegel_switch

# Notify iOS if switch is on but no one is home
- alias: "Skicka notis om eluttag är på men ingen är hemma"
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_switches
        state: 'on'

  action:
    - service: notify.ios_isaksiphone
      data:
        message: "Det verkar som att ingen är hemma men något eluttag är fortfarande på."

# Turn on light when someone comes home
- alias: "Slå på belysning när någon kommer hem"
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: switch.hall_light_spegel_switch

# Notify Erika when Isak comes home
- alias: "Isak kommer hem"
  trigger:
    platform: state
    entity_id: device_tracker.isaksiphone
    to: 'home'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.erikasiphone
        state: 'not_home'
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.erikasiphone
            state: 'jobbet'
          - condition: state
            entity_id: device_tracker.erikasiphone
            state: 'gymmet'
          - condition: state
            entity_id: device_tracker.erikasiphone
            state: 'ica_bea'

  action:
    - service: notify.ios_isaksiphone
      data:
        message: "Välkommen hem Isak. Lampan i hallen är nu tänd."

    - service: notify.ios_erikasiphone
      data:
        message: "Isak kom precis hem."

# Notify Isak when Erika comes home
- alias: "Erika kommer hem"
  trigger:
    platform: state
    entity_id: device_tracker.erikasiphone
    to: 'home'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.isaksiphone
        state: 'not_home'
      - condition: or
        conditions:
          - condition: state
            entity_id: device_tracker.isaksiphone
            state: 'jobbet'
          - condition: state
            entity_id: device_tracker.isaksiphone
            state: 'gymmet'
          - condition: state
            entity_id: device_tracker.isaksiphone
            state: 'ica_bea'

    action:
    - service: notify.ios_erikasiphone
      data:
        message: "Välkommen hem Erika. Lampan i hallen är nu tänd."

    - service: notify.ios_isaksiphone
      data:
        message: "Erika kom precis hem."
