homeassistant:
  name: Hemma
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 33
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include customize.yaml

frontend:
config:
updater:
map:
sun:
ios:
conversation:
tts:
  - platform: google
    language: sv

http:
  api_password: !secret http_password
  base_url: !secret http_address
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

discovery:
  ignore:
    - samsung_tv

zwave:
  usb_path: /dev/ttyACM0

device_tracker:
 - platform: asuswrt
   host: !secret router_ip
   username: !secret router_username
   password: !secret router_password
   protocol: telnet
   track_new_devices: true
   consider_home: 180
   interval_seconds: 12

history:
  include:
    entities:
      - device_tracker.erikasiphone
      - device_tracker.isaksiphone
      - media_player.vardagsrum
      - media_player.apple_tv
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_humidity
      - sensor.dark_sky_temperature
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - sensor.hall_light_spegel_power
      - sensor.isaks_iphone_battery_level
      - sensor.isaks_iphone_battery_state
      - sensor.erikas_iphone_battery_level
      - sensor.erikas_iphone_battery_state
      - sun.sun
      - switch.hall_light_spegel_switch

logbook:
  exclude:
    domains:
      - group
      - automation
      - media_player
      - sensor
      - zwave

sensor: !include sensors.yaml
group: !include groups.yaml
automation: !include_dir_list automations/
zone: !include zones.yaml
script: !include_dir_named scripts/
