# Home Assistant Configuration. Please see links below.
# https://github.com/doktorkugelschreiber/Home-Assistant-Configuration/blob/master/README.md
# https://home-assistant.io/getting-started/

homeassistant:
  name: Hemma
  latitude: !secret hass_latitude
  longitude: !secret hass_longitude
  elevation: 33
  unit_system: metric
  time_zone: Europe/Stockholm
  customize: !include config/customize.yaml

# https://home-assistant.io/docs/configuration/packages/
  packages: !include_dir_named config/packages/

# https://github.com/andrey-git/home-assistant-customizer
customizer:
  custom_ui: local
  hide_attributes:
    - node_id
    - value_index

# https://home-assistant.io/components/frontend/
frontend:
  themes: !include_dir_named config/themes/
  extra_html_url:
    - /local/custom_ui/state-card-custom-ui.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-custom-ui-es5.html
  javascript_version: auto

# Enable python script component. The scripts are stored in /python_scripts
python_script:

# https://home-assistant.io/docs/ecosystem/ios/
ios:
  push:
    categories:
      - name: CoffeeTimer
        identifier: 'coffeetimer'
        actions:
          - identifier: 'COFFEE_20_MINUTES'
            title: 'Det där sköter jag själv.'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'COFFEE_TURNOFF'
            title: 'Stäng av'
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: AlarmClock
        identifier: 'alarmclock'
        actions:
          - identifier: 'ALARM_AWAKE'
            title: 'Ja, nu'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'ALARM_AWAKE_SHOWER_FIRST'
            title: 'Ja, efter min dusch'
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'ALARM_NOT_AWAKE'
            title: 'Nej'
            activationMode: 'foreground'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'
      - name: ComingHomeAndSunIsUp
        identifier: 'cominghomeandsunisup'
        actions:
          - identifier: 'COMINGHOMEANDSUNISUP_YES'
            title: "Ja tack"
            activationMode: 'background'
            authenticationRequired: no
            destructive: no
            behavior: 'default'
          - identifier: 'COMINGHOMEANDSUNISUP_NO'
            title: "Nej tack"
            activationMode: 'background'
            authenticationRequired: no
            destructive: yes
            behavior: 'default'

# Enable text-to-speech
tts: !include config/tts.yaml

config:
updater:
map:
conversation:

http:
  api_password: !secret http_password
  base_url: !secret http_address
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 3

discovery:
  ignore:
    - samsung_tv

# Activate Z-Wave
zwave: !include config/zwave.yaml

# This shell command can be triggered from the service call component to disable the Z-Sticks flashing disco lights
shell_command:
  disco_off: echo -e -n "\x01\x08\x00\xF2\x51\x01\x00\x05\x01\x51" > /dev/ttyACM0

# Track devices from router connections
device_tracker: !include config/device_tracker.yaml

# Track the sun
sun:

# Enable history component
history: !include config/history.yaml

# Enable logbook component
logbook: !include config/logbook.yaml

# Inclusions
sensor: !include config/sensors.yaml
binary_sensor: !include config/binary_sensor.yaml
group: !include config/groups.yaml
automation: !include config/automations.yaml
zone: !include config/zones.yaml
script: !include config/scripts.yaml
scene: !include config/scenes.yaml
