# TV Pack

# HDMI Cec
hdmi_cec:
  devices:
    2: Telia TV
    3: Apple TV

# On/off switch
switch:
  - platform: template
    switches:
      samsung_tv:
        friendly_name: "TV"
        value_template: "{{ is_state('switch.hdmi_0', 'on') }}"
        turn_on:
          service: hdmi_cec.power_on
        turn_off:
          service: hdmi_cec.standby

# HDMI Input select
input_select:
  hdmisource:
    name: "Välj källa"
    icon: mdi:video-input-hdmi
    options:
      - "--Välj--"
      - "Telia TV"
      - "Apple TV"

# Group
group:
  tvcontrol:
    name: "TV"
    entities:
      - switch.samsung_tv
      - switch.hdmi_4
      - input_select.hdmisource

# Automation
automation:
  - alias: "Välj HDMI-källa"
    hide_entity: true

    trigger:
      platform: state
      entity_id: input_select.hdmisource

    action:
      - service: hdmi_cec.select_device
        data_template:
          device: >
            {% if is_state("input_select.hdmisource", "Telia TV") %}
              Telia TV
            {% elif is_state("input_select.hdmisource", "Apple TV") %}
              Apple TV
            {% endif %}
      - delay: 00:00:02
      - service: input_select.select_option
        data:
          entity_id: input_select.hdmisource
          option: "--Välj--"
