- alias: "Händelse - Solnedgång"
  trigger:
    platform: sun
    event: sunset
    offset: '-00:00:15'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Småbelysning"
- alias: "Händelse - Hemkomst"
  trigger:
    platform: state
    entity_id: group.all_devices
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Småbelysning"
- alias: "Händelse - TV på"
  trigger:
    platform: state
    entity_id: binary_sensor.samsung_tv_ping
    to: 'on'

  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "TV"
- alias: "Händelse - TV av"
  trigger:
    platform: state
    entity_id: binary_sensor.samsung_tv_ping
    to: 'off'

  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunset
        after_offset: "-01:00:00"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Småbelysning"
- alias: "Händelse - Båda gått hemifrån"
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: group.all_switches
        state: 'on'
      - condition: state
        entity_id: group.all_lights
        state: 'on'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Borta"

    - service: notify.ios_isaksiphone
      data:
        title: "Automation"
        message: "Släckt och stängt av hemma."
- alias: "Händelse - Erika hemma"
  trigger:
    platform: state
    entity_id: device_tracker.erikasiphone
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.device_tracker.isaksiphone.state == "not_home" }}'
  action:
    - service: notify.ios_isaksiphone
      data:
        message: "Erika kom precis hem."
    - service: notify.ios_erikasiphone
      data_template:
        title: "Hej Erika"
        message: >
          {% if is_state('sun.sun', 'below_horizon') %}
            Det är mörkt ute. Jag har tänt åt dig.
          {% else %}
            Det är fortfarande ljust. Vill du tända lite lampor?
          {% endif %}
        data:
          push:
            category:
              "cominghomeandsunisup"
- alias: "Händelse - Isak hemma"
  trigger:
    platform: state
    entity_id: device_tracker.isaksiphone
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: '{{ states.device_tracker.erikasiphone.state == "not_home" }}'
  action:
    - service: notify.ios_isaksiphone
      data:
        message: "Välkommen hem Isak."
    - service: notify.ios_erikasiphone
      data:
        message: "Isak kom precis hem."
- alias: "Händelse - Köket tomt dagtid"
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_aeotec_sensor
    to: 'off'
    for:
      minutes: 30
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: switch.kitchen_tolomeo_switch
        state: 'on'
      - condition: state
        entity_id: light.kitchen_spotlight_level
        state: 'on'
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_tolomeo_switch
    - service: light.turn_off
      entity_id: light.kitchen_spotlight_level
    - service: notify.ios_isaksiphone
      data:
        title: "Automation"
        message: "Belysningen i köket nedtonad."
- alias: "Händelse - Rörelse i köket (sover)"
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_aeotec_sensor
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.scenepicker
        state: "Sova"
      - condition: state
        entity_id: input_select.scenepicker
        state: "Läggdags"
  action:
    - service: switch.turn_on
      entity_id: switch.kitchen_window_switch
- alias: "Händelse - Tomt i köket (sover)"
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_aeotec_sensor
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.scenepicker
        state: "Sova"
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_window_switch
- alias: "Notis - Hög luftfuktighet i köket"
  trigger:
    platform: numeric_state
    entity_id: sensor.bathroom_aeotec_relative_humidity
    above: 60
  action:
    - service: notify.ios_isaksiphone
      data:
        title: "Åtgärd krävs"
        message: "Luftfuktigheten i köket är över 60 %. Överväg att öppna ett fönster."
- alias: "Timer - Luftavfuktare"
  trigger:
    platform: state
    entity_id: switch.bathroom_wallplug_switch
    to: 'on'
    for:
      hours: 1
  action:
    - service: switch.turn_off
      entity_id: switch.bathroom_wallplug_switch
    - service: notify.ios_isaksiphone
      data:
        title: "Automation"
        message: "Luftavfuktaren stängdes av efter 1 timme."
- alias: "Timer - Kaffebryggare"
  trigger:
    platform: state
    entity_id: switch.kitchen_coffeebrewer_switch
    to: 'on'
    for:
      hours: 1
  action:
    - service: notify.ios_isaksiphone
      data:
        title: "Timer"
        message: "Kaffebryggaren har varit på en timme. Vill du stänga av den?"
        data:
          push:
            category: 'coffeetimer'
    - service: notify.ios_erikasiphone
      data:
        title: "Timer"
        message: "Kaffebryggaren har varit på en timme. Vill du stänga av den?"
        data:
          push:
            category: 'coffeetimer'

# Väckarklocka
- alias: "Väckarklocka - Kör automation när rörelse i köket"
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.bathroom_aeotec_sensor
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.alarm_triggered_run_automations
        state: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Morgon"
    - service: homeassistant.turn_off
      entity_id: input_boolean.alarm_triggered_run_automations

# iOS Notification automations - hidden from frontend
- alias: "iOS - Val: Stäng av kaffebryggare"
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: COFFEE_TURNOFF
  action:
    - service: switch.turn_off
      entity_id: switch.kitchen_coffeebrewer_switch
- alias: "iOS - Val: Tänd belysning"
  hide_entity: true
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: COMINGHOMEANDSUNISUP_YES
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scenepicker
        option: "Småbelysning"

# Entity counter automation - hidden from frontend
- alias: "Update entities on" # (requirement: config/python_scripts/count_entities_on.py)
  hide_entity: true
  trigger:
    - platform: state
      entity_id:
        - switch.hall_spegel_switch
        - switch.bedroom_window_switch
        - switch.kitchen_window_switch
        - switch.kitchen_tolomeo_switch
        - switch.kitchen_coffeebrewer_switch
        - switch.livingroom_window_switch
        - light.bedroom_isakbedside_level
        - light.bedroom_erikabedside_level
        - light.kitchen_spotlight_level
        - light.livingroom_cornerlight_level
    - platform: homeassistant
      event: start
  action:
    - service: python_script.count_entities_on
