  - platform: command_line
    name: samsung_tv_ping
    scan_interval: 15
    command: 'ping -W 1 -c 1 192.168.0.113 > /dev/null 2>&1 && echo success || echo fail'
    payload_on: success
    payload_off: fail
