####################################################
#                                                  #
#                     SWITCHES                     #
#                                                  #
####################################################
# Hallen
switch.hall_spegel_switch:
  friendly_name: Spegel
  icon: mdi:lightbulb
  homebridge_visible: true

# Vardagsrummet
switch.livingroom_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true

light.livingroom_cornerlight_level:
  friendly_name: Soffan
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

switch.samsung_tv:
  icon: mdi:television
  homebridge_visible: true
  homebridge_switch_type: outlet

# Sovrummet
switch.bedroom_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true

light.bedroom_isakbedside_level:
  friendly_name: "Isaks sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

light.bedroom_erikabedside_level:
  friendly_name: "Erikas sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

# Köket
switch.kitchen_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true

switch.kitchen_tolomeo_switch:
  friendly_name: Tolomeo
  icon: mdi:lightbulb
  homebridge_visible: true

light.kitchen_spotlight_level:
  friendly_name: "Spotlight"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

switch.kitchen_coffeebrewer_switch:
  friendly_name: Kaffebryggare
  homebridge_visible: true
  homebridge_switch_type: outlet
  custom_ui_state_card: state-card-custom-ui
  show_last_changed: true

####################################################
#                                                  #
#                   MEDIA PLAYERS                  #
#                                                  #
####################################################
media_player.vardagsrum:
  friendly_name: Vardagsrum

media_player.apple_tv:
  friendly_name: "Apple TV"

####################################################
#                                                  #
#                     SENSORS                      #
#                                                  #
####################################################
sensor.isaks_iphone_battery_level:
  friendly_name: "Isaks iPhone"

sensor.erikas_iphone_battery_level:
  friendly_name: "Erikas iPhone"

sensor.hall_spegel_power:
  icon: mdi:lightbulb
  friendly_name: "Hall: Spegel"

sensor.livingroom_window_power:
  icon: mdi:lightbulb
  friendly_name: "Vardagsrum: Fönster"

sensor.bedroom_window_power:
  icon: mdi:lightbulb
  friendly_name: "Sovrum: Fönster"

sensor.kitchen_window_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Fönster"

sensor.kitchen_tolomeo_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Tolomeo"

sensor.kitchen_spotlight_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Spotlight"

sensor.kitchen_coffeebrewer_power:
  friendly_name: "Kök: Kaffebryggare"
  icon: mdi:flash

sensor.memory_use_percent:
  friendly_name: "RAM"

sensor.processor_use:
  friendly_name: "CPU"

sensor.disk_use_percent_:
  friendly_name: "HDD"

sensor.since_last_boot:
  friendly_name: "Uptime"

####################################################
#                                                  #
#                 INTERNET SENSORS                 #
#                                                  #
####################################################
sensor.dark_sky_cloud_coverage:
  friendly_name: Moln
  icon: mdi:cloud

sensor.dark_sky_precip_intensity:
  friendly_name: Regn
  icon: mdi:weather-rainy

sensor.dark_sky_temperature:
  friendly_name: Temp
  icon: mdi:thermometer

sensor.dark_sky_wind_speed:
  friendly_name: Vind
  icon: mdi:weather-windy

####################################################
#                                                  #
#                  INPUT SELECT                    #
#                                                  #
####################################################
input_select.scenepicker:
  friendly_name: "Scen"

####################################################
#                                                  #
#                     ZONING                       #
#                                                  #
####################################################
zone.home:
  track_ios: false
