# Hallen
switch.hall_spegel_switch:
  friendly_name: Spegel
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0

# Vardagsrummet
light.livingroom_cornerlight_level:
  friendly_name: Soffan
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true
switch.livingroom_window_switch:
  friendly_name: Vardagsrumsfönster
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0
media_player.vardagsrum:
  friendly_name: "Sonos Playbar"
media_player.apple_tv:
  friendly_name: "Apple TV"
binary_sensor.samsung_tv_ping:
  icon: mdi:television
  friendly_name: TV

# Sovrummet
light.bedroom_isakbedside_level:
  friendly_name: "Isaks sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true
light.bedroom_erikabedside_level:
  friendly_name: "Erikas sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true
switch.bedroom_window_switch:
  friendly_name: Sovrumsfönster
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0

# Köket
light.kitchen_spotlight_level:
  friendly_name: "Spotlight"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0
switch.kitchen_window_switch:
  friendly_name: Köksfönster
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0
switch.kitchen_tolomeo_switch:
  friendly_name: Tolomeo
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0
switch.kitchen_coffeebrewer_switch:
  friendly_name: Kaffebryggare
  icon: mdi:water
  homebridge_visible: true
  homebridge_switch_type: outlet
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0

# Badrummet
switch.bathroom_wallplug_switch:
  icon: mdi:fan
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    attribute: power_consumption
    unit: W
    blacklist_states: 0

# Tekniska sensorer
sensor.memory_use_percent:
  friendly_name: "RAM"
sensor.processor_use:
  friendly_name: "CPU"
sensor.disk_use_percent_:
  friendly_name: "HDD"
sensor.since_last_boot:
  friendly_name: "Uptime"

# Vädersensorer
sensor.dark_sky_cloud_coverage:
  friendly_name: Moln
  icon: mdi:cloud
sensor.dark_sky_precip_intensity:
  friendly_name: Regn
  icon: mdi:weather-rainy
sensor.dark_sky_temperature:
  friendly_name: Temp
  icon: mdi:thermometer
sensor.dark_sky_wind_speed:
  friendly_name: Vind
  icon: mdi:weather-windy

# Grupper
group.all_automations:
  hidden: false
  friendly_name: Automationer
group.sub1_1_1:
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: badges

# Zoner
zone.home:
  track_ios: false

# Input select
input_select.scenepicker:
  friendly_name: "Scen"


sensor.bathroom_aeotec_relative_humidity:
  icon: mdi:water-percent

sensor.bathroom_aeotec_luminance:
  icon: mdi:theme-light-dark
