####################################################
#                                                  #
#                     SWITCHES                     #
#                                                  #
####################################################
# Hallen
switch.hall_spegel_switch:
  friendly_name: Spegel
  icon: mdi:lightbulb
  homebridge_visible: true

# Vardagsrummet
switch.livingroom_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true

light.livingroom_cornerlight_level:
  friendly_name: Soffan
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

# Sovrummet
switch.bedroom_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true

light.bedroom_isakbedside_level:
  friendly_name: "Isaks sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

light.bedroom_erikabedside_level:
  friendly_name: "Erikas sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

# Köket
switch.kitchen_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true

switch.kitchen_coffeebrewer_switch:
  friendly_name: Kaffebryggare
  homebridge_visible: true

####################################################
#                                                  #
#                   MEDIA PLAYERS                  #
#                                                  #
####################################################
media_player.vardagsrum:
  friendly_name: Vardagsrum

media_player.apple_tv:
  friendly_name: "Apple TV"

####################################################
#                                                  #
#                     SENSORS                      #
#                                                  #
####################################################
sensor.isaks_iphone_battery_level:
  friendly_name: "Isaks iPhone"

sensor.erikas_iphone_battery_level:
  friendly_name: "Erikas iPhone"

sensor.hall_spegel_power:
  icon: mdi:lightbulb
  friendly_name: "Hall: Spegel"

sensor.livingroom_window_power:
  icon: mdi:lightbulb
  friendly_name: "Vardagsrum: Fönster"

sensor.bedroom_window_power:
  icon: mdi:lightbulb
  friendly_name: "Sovrum: Fönster"

sensor.kitchen_window_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Fönster"

sensor.kitchen_coffeebrewer_power:
  friendly_name: "Kök: Kaffebryggare"
  icon: mdi:flash

sensor.ram_used:
  friendly_name: "Användning av RAM-minne"

sensor.cpu_used:
  friendly_name: "Användning av processor"

sensor.disk_used_:
  friendly_name: "Användning av hårddisk"

sensor.since_last_boot:
  friendly_name: "Tid sedan systemstart"

####################################################
#                                                  #
#                 INTERNET SENSORS                 #
#                                                  #
####################################################
sensor.dark_sky_cloud_coverage:
  friendly_name: Moln
  icon: mdi:cloud

sensor.dark_sky_precip_intensity:
  friendly_name: Regn
  icon: mdi:weather-rainy

sensor.dark_sky_temperature:
  friendly_name: Temp
  icon: mdi:thermometer

sensor.dark_sky_wind_speed:
  friendly_name: Vind
  icon: mdi:weather-windy

####################################################
#                                                  #
#                  INPUT SELECT                    #
#                                                  #
####################################################
input_select.scenepicker:
  friendly_name: "Scen"
