####################################################
#                                                  #
#                     SWITCHES                     #
#                                                  #
####################################################
# Hallen
switch.hall_spegel_switch:
  friendly_name: Spegel
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.hall_spegel_power
    blacklist_states: 0

# Vardagsrummet
switch.livingroom_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.livingroom_window_power
    blacklist_states: 0

light.livingroom_cornerlight_level:
  friendly_name: Soffan
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

switch.samsung_tv:
  icon: mdi:television
  homebridge_visible: true
  homebridge_switch_type: outlet

switch.hdmi_4:
  icon: mdi:television-box
  friendly_name: "Telia TV"

# Sovrummet
switch.bedroom_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.bedroom_window_power
    blacklist_states: 0

light.bedroom_isakbedside_level:
  friendly_name: "Isaks sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

light.bedroom_erikabedside_level:
  friendly_name: "Erikas sänglampa"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true

# Köket
switch.kitchen_window_switch:
  friendly_name: Fönster
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.kitchen_window_power
    blacklist_states: 0

switch.kitchen_tolomeo_switch:
  friendly_name: Tolomeo
  icon: mdi:lightbulb
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.kitchen_tolomeo_power
    blacklist_states: 0

light.kitchen_spotlight_level:
  friendly_name: "Spotlight"
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  state_card_mode: break-slider
  stretch_slider: true
  extra_badge:
    entity_id: sensor.kitchen_spotlight_power
    blacklist_states: 0

switch.kitchen_coffeebrewer_switch:
  friendly_name: Kaffebryggare
  icon: mdi:water
  homebridge_visible: true
  homebridge_switch_type: outlet
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.kitchen_coffeebrewer_power
    blacklist_states: 0

# Badrummet
switch.bathroom_wallplug_switch:
  icon: mdi:fan
  homebridge_visible: true
  custom_ui_state_card: state-card-custom-ui
  extra_badge:
    entity_id: sensor.bathroom_wallplug_switch
    blacklist_states: 0

####################################################
#                                                  #
#                   MEDIA PLAYERS                  #
#                                                  #
####################################################
media_player.vardagsrum:
  friendly_name: "Sonos Playbar"

media_player.apple_tv:
  friendly_name: "Apple TV"

####################################################
#                                                  #
#                     SENSORS                      #
#                                                  #
####################################################
sensor.isaks_iphone_battery_level:
  friendly_name: "Isaks iPhone"

sensor.erikas_iphone_battery_level:
  friendly_name: "Erikas iPhone"

sensor.hall_spegel_power:
  icon: mdi:lightbulb
  friendly_name: "Hall: Spegel"

sensor.livingroom_window_power:
  icon: mdi:lightbulb
  friendly_name: "Vardagsrum: Fönster"

sensor.bedroom_window_power:
  icon: mdi:lightbulb
  friendly_name: "Sovrum: Fönster"

sensor.kitchen_window_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Fönster"

sensor.kitchen_tolomeo_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Tolomeo"

sensor.kitchen_spotlight_power:
  icon: mdi:lightbulb
  friendly_name: "Kök: Spotlight"

sensor.kitchen_coffeebrewer_power:
  friendly_name: "Kök: Kaffebryggare"
  icon: mdi:flash

sensor.memory_use_percent:
  friendly_name: "RAM"

sensor.processor_use:
  friendly_name: "CPU"

sensor.disk_use_percent_:
  friendly_name: "HDD"

sensor.since_last_boot:
  friendly_name: "Uptime"

sensor.bathroom_aeotec_relative_humidity:
  icon: mdi:water-percent

sensor.bathroom_aeotec_temperature:
  icon: mdi:theme-light-dark

####################################################
#                                                  #
#                 INTERNET SENSORS                 #
#                                                  #
####################################################
sensor.dark_sky_cloud_coverage:
  friendly_name: Moln
  icon: mdi:cloud

sensor.dark_sky_precip_intensity:
  friendly_name: Regn
  icon: mdi:weather-rainy

sensor.dark_sky_temperature:
  friendly_name: Temp
  icon: mdi:thermometer

sensor.dark_sky_wind_speed:
  friendly_name: Vind
  icon: mdi:weather-windy

####################################################
#                                                  #
#                  INPUT SELECT                    #
#                                                  #
####################################################
input_select.scenepicker:
  friendly_name: "Scen"

####################################################
#                                                  #
#                     ZONING                       #
#                                                  #
####################################################
zone.home:
  track_ios: false
