- platform: asuswrt
  host: !secret router_ip
  username: !secret router_username
  password: !secret router_password
  protocol: telnet
  track_new_devices: true
  consider_home: 180
  interval_seconds: 12
