######################################
#           View in frontend         #
######################################
# What to view on home page
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - device_tracker.erikasiphone
      - device_tracker.isaksiphone
      - sensor.alarm_activated_badge
      - sensor.dark_sky_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_wind_speed
      - group.scenepicker
      - group.hall
      - group.vardagsrum
      - group.kitchen
      - group.bedroom
      - group.alarmclock

# What to view on media page
  media:
    name: Media
    icon: mdi:itunes
    view: yes
    entities:
      - group.tvcontrol
      - media_player.vardagsrum
      - media_player.sovrum
      - media_player.apple_tv

# What to view on sensors page
  sensors:
    name: Sensorer
    view: yes
    icon: mdi:gauge
    entities:
      - group.batteries
      - group.powerconsumption
      - group.system
      - group.pollenkoll

# What to view on automations page
  robot:
    name: Robot
    view: yes
    icon: mdi:robot
    entities:
      - group.countdowns
      - group.automatic_scenes
      - group.notifications


######################################
#         Groups within groups       #
######################################
# Groups within front page
  hall:
    name: Hall
    entities:
      - switch.hall_spegel_switch

  vardagsrum:
    name: Vardagsrum
    entities:
      - switch.livingroom_window_switch
      - light.livingroom_cornerlight_level
      - switch.samsung_tv

  kitchen:
    name: "Kök"
    entities:
      - switch.kitchen_window_switch
      - light.kitchen_spotlight_level
      - switch.kitchen_tolomeo_switch
      - switch.kitchen_coffeebrewer_switch

  bedroom:
    name: Sovrum
    entities:
      - switch.bedroom_window_switch
      - light.bedroom_erikabedside_level
      - light.bedroom_isakbedside_level

# Groups within sensors page
  powerconsumption:
    name: "Elförbrukning"
    entities:
      - sensor.hall_spegel_power
      - sensor.livingroom_window_power
      - sensor.bedroom_window_power
      - sensor.kitchen_window_power
      - sensor.kitchen_tolomeo_power
      - sensor.kitchen_spotlight_power
      - sensor.kitchen_coffeebrewer_power

  system:
    name: "Systemstatus"
    entities:
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.disk_use_percent_
      - sensor.since_last_boot

  batteries:
    name: Batterier
    entities:
      - sensor.erikas_iphone_battery_level
      - sensor.isaks_iphone_battery_level

# Groups within automations page
  countdowns:
    name: Timers
    entities:
        - automation.kaffebryggare_av_efter_60_minuter

  automatic_scenes:
    name: Automatiska scenkörningar
    entities:
      - automation.kor_hemmalage_vid_solnedgangen
      - automation.kor_hemmalage_vid_hemkomst_efter_solnedgangen
      - automation.starta_tvlage_da_apple_tv_spelar_efter_solnedgang
      - automation.starta_timer_da_apple_tv_pausar_efter_solnedgang

  notifications:
    name: Notifieringar
    entities:
      - automation.erika_kommer_hem
      - automation.isak_kommer_hem
      - automation.skicka_notis_om_eluttag_ar_pa_men_ingen_ar_hemma
