######################################
#           View in frontend         #
######################################
# What to view on home page
  default_view:
    view: yes
    icon: mdi:home
    entities:
      - device_tracker.erikasiphone
      - device_tracker.isaksiphone
      - sensor.entities_on
      - sensor.alarm_activated_badge
      - group.hall
      - group.vardagsrum
      - group.kitchen
      - group.bedroom

# What to view on weather page
  weather:
    name: Weather
    icon: mdi:thermometer-lines
    view: yes
    entities:
      - group.weather_card_today
      - group.weather_card_forecast
      - group.pollenkoll

# What to view on automations page
  settings:
    name: Settings
    view: yes
    icon: mdi:tune
    entities:
      - group.scenepicker
      - group.alarmclock
      - group.countdowns
      - group.automatic_scenes
      - group.notifications

# What to view on sensors page
  sensors:
    name: Sensorer
    view: yes
    icon: mdi:gauge
    entities:
      - group.batteries
      - group.powerconsumption
      - group.system

# What to view on media page
  media:
    name: Media
    icon: mdi:itunes
    view: yes
    entities:
      - group.tvcontrol
      - media_player.vardagsrum
      - media_player.sovrum
      - media_player.apple_tv


######################################
#         Groups within groups       #
######################################
# Groups within front page
  hall:
    name: Hall
    entities:
      - switch.hall_spegel_switch

  vardagsrum:
    name: Vardagsrum
    entities:
      - switch.livingroom_window_switch
      - light.livingroom_cornerlight_level
      - switch.samsung_tv
      - switch.sonos_livingroom

  kitchen:
    name: "Kök"
    entities:
      - switch.kitchen_window_switch
      - light.kitchen_spotlight_level
      - switch.kitchen_tolomeo_switch
      - switch.kitchen_coffeebrewer_switch

  bedroom:
    name: Sovrum
    entities:
      - switch.bedroom_window_switch
      - light.bedroom_erikabedside_level
      - light.bedroom_isakbedside_level
      - switch.sonos_bedroom

# Groups within sensors page
  powerconsumption:
    name: "Elförbrukning"
    entities:
      - sensor.hall_spegel_power
      - sensor.livingroom_window_power
      - sensor.bedroom_window_power
      - sensor.kitchen_window_power
      - sensor.kitchen_tolomeo_power
      - sensor.kitchen_spotlight_power
      - sensor.kitchen_coffeebrewer_power

  system:
    name: "Systemstatus"
    entities:
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.disk_use_percent_
      - sensor.since_last_boot

  batteries:
    name: Batterier
    entities:
      - sensor.erikas_iphone_battery_level
      - sensor.isaks_iphone_battery_level

# Groups within automations page
  countdowns:
    name: Timers
    entities:
        - automation.kaffebryggare_av_efter_60_minuter

  automatic_scenes:
    name: Automatiska scenkörningar
    entities:
      - automation.scen_hemma_vid_hemkomst_och_morkt
      - automation.scen_hemma_vid_solnedgang
      - automation.scen_tv_da_apple_tv_spelar
      - automation.scen_hemma_da_apple_tv_pausas

  notifications:
    name: Notifieringar
    entities:
      - automation.erika_kommer_hem
      - automation.isak_kommer_hem
      - automation.nagot_ar_pa_och_ingen_ar_hemma
