#####         MAIN GROUP 1        #####
##### Home/Default view/Dashboard #####
  default_view:
    view: yes
    icon: mdi:home
    entities:
      # badges
      - device_tracker.erikasiphone
      - device_tracker.isaksiphone
      - sensor.entities_on
      - sensor.alarm_activated_badge
      # subgroups
      - group.sub1_1
      - group.sub1_2
      - group.sub1_3
      - group.sub1_4
      - group.sub1_5

# Subgroup 1.1
  sub1_1:
    name: "Kök"
    control: hidden
    entities:
      - switch.kitchen_window_switch
      - light.kitchen_spotlight_level
      - switch.kitchen_tolomeo_switch
      - switch.kitchen_coffeebrewer_switch

# Subgroup 1.2
  sub1_2:
    name: Vardagsrum
    control: hidden
    entities:
      - switch.livingroom_window_switch
      - light.livingroom_cornerlight_level
      - switch.samsung_tv
      - switch.hdmi_4

# Subgroup 1.3
  sub1_3:
    name: Sovrum
    control: hidden
    entities:
      - switch.bedroom_window_switch
      - light.bedroom_erikabedside_level
      - light.bedroom_isakbedside_level

# Subgroup 1.4
  sub1_4:
    name: Hall
    entities:
      - switch.hall_spegel_switch

# Subgroup 1.5
  sub1_5:
    name: Badrum
    entities:
      - switch.bathroom_wallplug_switch
      - binary_sensor.bathroom_aeotec_sensor
      - sensor.bathroom_aeotec_temperature
      - sensor.bathroom_aeotec_relative_humidity
      - sensor.bathroom_aeotec_luminance

#######################################
#####         MAIN GROUP 2        #####
#####           Kitchen           #####
#######################################
  kitchen:
    view: yes
    name: "Kök"
    entities:
      - group.sub2_1
      - group.sub2_2

# Subgroup 2.1
  sub2_1:
    name: "Lampor"
    control: hidden
    entities:
      - switch.kitchen_window_switch
      - light.kitchen_spotlight_level
      - switch.kitchen_tolomeo_switch

# Subgroup 2.2
  sub2_2:
    name: "Kaffebryggare"
    control: hidden
    entities:
      - switch.kitchen_coffeebrewer_switch
      - automation.kaffebryggare_av_efter_60_minuter


#######################################
#####         MAIN GROUP 3        #####
#####         Living room         #####
#######################################
  livingroom:
    view: yes
    name: "Vardagsrum"
    entities:
      - group.sub3_1
      - group.tvcontrol
      - media_player.vardagsrum
      - media_player.apple_tv

# Subgroup 3.1
  sub3_1:
    name: "Lampor"
    control: hidden
    entities:
      - switch.livingroom_window_switch
      - light.livingroom_cornerlight_level


#######################################
#####         MAIN GROUP 4        #####
#####           Bedroom           #####
#######################################
  bedroom:
    view: yes
    name: "Sovrum"
    entities:
      - group.sub4_1
      - media_player.sovrum
      - group.alarmclock

# Subgroup 4.1
  sub4_1:
    name: "Lampor"
    control: hidden
    entities:
      - switch.bedroom_window_switch
      - light.bedroom_erikabedside_level
      - light.bedroom_isakbedside_level


#######################################
#####         MAIN GROUP 5        #####
#####            Hall             #####
#######################################
  hall:
    view: yes
    name: "Hall"
    entities:
      - group.sub5_1

# Subgroup 5.1
  sub5_1:
    name: "Lampor"
    entities:
      - switch.hall_spegel_switch


#######################################
#####         MAIN GROUP 6        #####
#####           Weather           #####
#######################################
  weather:
    name: Weather
    icon: mdi:thermometer-lines
    view: yes
    entities:
      - group.weather_card_today
      - group.weather_card_forecast
      - group.almanacka
      - group.pollenkoll


#######################################
#####         MAIN GROUP 7        #####
#####           Settings          #####
#######################################
# Settings
  settings:
    name: Settings
    view: yes
    icon: mdi:tune
    entities:
      - group.scenepicker
      - group.automatic_scenes
      - group.notifications

  automatic_scenes:
    name: Automatiska scenkörningar
    entities:
      - automation.scen_hemma_vid_hemkomst_och_morkt
      - automation.scen_hemma_vid_solnedgang
      - automation.scen_tv_da_apple_tv_spelar
      - automation.scen_hemma_da_apple_tv_pausas

  notifications:
    name: Notifieringar
    entities:
      - automation.erika_kommer_hem
      - automation.erika_nastan_hemma
      - automation.isak_kommer_hem
      - automation.isak_nastan_hemma
      - automation.nagot_ar_pa_och_ingen_ar_hemma


#######################################
#####         MAIN GROUP 8        #####
#####           Sensors           #####
#######################################
  sensors:
    name: Sensorer
    view: yes
    icon: mdi:gauge
    entities:
      - group.batteries
      - group.powerconsumption
      - group.system

  powerconsumption:
    name: "Elförbrukning"
    entities:
      - sensor.hall_spegel_power
      - sensor.livingroom_window_power
      - sensor.bedroom_window_power
      - sensor.kitchen_window_power
      - sensor.kitchen_tolomeo_power
      - sensor.kitchen_spotlight_power
      - sensor.kitchen_coffeebrewer_power

  system:
    name: "Systemstatus"
    entities:
      - sensor.memory_use_percent
      - sensor.processor_use
      - sensor.disk_use_percent_
      - sensor.since_last_boot

  batteries:
    name: Batterier
    entities:
      - sensor.erikas_iphone_battery_level
      - sensor.isaks_iphone_battery_level
