use_include_order: true
include:
  entities:
    - device_tracker.erikasiphone
    - device_tracker.isaksiphone
    - switch.samsung_tv
    - media_player.vardagsrum
    - media_player.sovrum
    - sun.sun
    - switch.hall_spegel_switch
    - switch.kitchen_window_switch
    - switch.kitchen_coffeebrewer_switch
    - switch.kitchen_tolomeo_switch
    - light.kitchen_spotlight_level
    - switch.livingroom_window_switch
    - light.livingroom_cornerlight_level
    - switch.bedroom_window_switch
    - light.bedroom_erikabedside_level
    - light.bedroom_isakbedside_level
