# System health information
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use

# Uptime
  - platform: uptime

# Z Wave battery devices
  - platform: template
    sensors:
      battery_aeotec:
        friendly_name: "Aeotec 1"
        value_template: "{{states.zwave.bathroom_aeotec.attributes['battery_level']}}"
