- name: p책 jobbet
  latitude: !secret work_latitude
  longitude: !secret work_longitude
  radius: 500
  icon: mdi:briefcase

- name: p책 gymmet
  latitude: !secret gym_latitude
  longitude: !secret gym_longitude
  radius: 200
  icon: mdi:weight-kilogram

- name: p책 ICA
  latitude: !secret shop_latitude
  longitude: !secret shop_longitude
  icon: mdi:cart

- name: p책 universitetet
  latitude: !secret university_latitude
  longitude: !secret university_longitude
  icon: mdi:school
  radius: 300
