sensor.hall_light_spegel_alarm_level:
  ignored: true
  polling_intensity: 0
sensor.hall_light_spegel_alarm_type:
  ignored: true
  polling_intensity: 0
sensor.hall_light_spegel_exporting:
  ignored: true
  polling_intensity: 0
sensor.hall_light_spegel_power_management:
  ignored: true
  polling_intensity: 0
sensor.hall_light_spegel_sourcenodeid:
  ignored: true
  polling_intensity: 0
