# Notify Isak when Erika comes home
alias: "Erika kommer hem"
trigger:
  platform: state
  entity_id: device_tracker.erikasiphone
  to: 'home'

condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.device_tracker.isaksiphone.state != home }}'

action:
  - service: notify.ios_isaksiphone
    data:
      message: "Erika kom precis hem."
  - service: notify.ios_erikasiphone
    data:
      title: "Hej Erika"
      message: "Ska jag tända lite?"
      data:
        push:
          category:
            "cominghomeandsunisup"
