# Notify Erika when Isak comes home
alias: "Isak kommer hem"
trigger:
  platform: state
  entity_id: device_tracker.isaksiphone
  to: 'home'

condition:
  condition: and
  conditions:
    - condition: template
      value_template: '{{ states.device_tracker.erikasiphone.state != home }}'

action:
  - service: notify.ios_isaksiphone
    data:
      message: "Välkommen hem Isak."

  - service: notify.ios_erikasiphone
    data:
      message: "Isak kom precis hem."
