# Automatically turn everything off
alias: "Något är på och ingen är hemma"
trigger:
  platform: state
  entity_id: group.all_devices
  from: 'home'

condition:
  condition: or
  conditions:
    - condition: state
      entity_id: group.all_switches
      state: 'on'
    - condition: state
      entity_id: group.all_lights
      state: 'on'

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.scenepicker
      option: "Borta"

  - service: notify.ios_isaksiphone
    data:
      message: "Du glömde släcka innan du gick. Jag har gjort det åt dig."

  - service: notify.ios_erikasiphone
    data:
      message: "Du glömde släcka innan du gick. Jag har gjort det åt dig."
