# Run coffee timer script when coffee timer is started
alias: "Kaffebryggare av efter 45 minuter"
trigger:
  platform: state
  entity_id: switch.kitchen_coffeebrewer_switch
  to: 'on'

action:
  - service: script.turn_on
    entity_id: script.coffeecountdown
