# Run evening script when someone comes home after sunset
alias: "Kör kvällsläge vid hemkomst efter solnedgången"
trigger:
  platform: state
  entity_id: group.all_devices
  to: 'home'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'

action:
  - service: script.turn_on
    entity_id: script.evening
  - service: script.turn_on
    entity_id: script.logger_coming_home
