# Notify Isak when Erika comes home
alias: "Erika kommer hem"
trigger:
  platform: state
  entity_id: device_tracker.erikasiphone
  to: 'home'

condition:
  condition: or
  conditions:
    - condition: state
      entity_id: device_tracker.isaksiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.isaksiphone
      state: 'jobbet'
    - condition: state
      entity_id: device_tracker.isaksiphone
      state: 'gymmet'
    - condition: state
      entity_id: device_tracker.isaksiphone
      state: 'ica'
    - condition: state
      entity_id: device_tracker.isaksiphone
      state: 'universitetet'

action:
  - service: notify.ios_erikasiphone
    data:
      message: "Välkommen hem Erika. Belysningen är tänd."

  - service: notify.ios_isaksiphone
    data:
      message: "Erika kom precis hem."
