# Notify Erika when Isak comes home
alias: "Isak kommer hem"
trigger:
  platform: state
  entity_id: device_tracker.isaksiphone
  to: 'home'

condition:
  condition: or
  conditions:
    - condition: state
      entity_id: device_tracker.erikasiphone
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.erikasiphone
      state: 'jobbet'
    - condition: state
      entity_id: device_tracker.erikasiphone
      state: 'gymmet'
    - condition: state
      entity_id: device_tracker.erikasiphone
      state: 'ica'
    - condition: state
      entity_id: device_tracker.erikasiphone
      state: 'universitetet'

action:
  - service: notify.ios_isaksiphone
    data:
      message: "Välkommen hem Isak. Belysningen är tänd."

  - service: notify.ios_erikasiphone
    data:
      message: "Isak kom precis hem."
