# Run evening script at sunset if someone is home
alias: "G책 till kv채llsl채ge vid solnedg책ngen"
trigger:
  platform: sun
  event: sunset
  offset: '-01:00:00'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.all_devices
      state: 'home'

action:
  - service: script.turn_on
    entity_id: script.evening
  - service: script.turn_on
    entity_id: script.logger_sunset
