# Lamps on at sunset and someone is home
- alias: "Automatisk belysning vid solnedgång"
  trigger:
    platform: sun
    event: sunset
    offset: '-01:00:00'

  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.all_devices
        state: 'home'

  action:
    - service: homeassistant.turn_on
      entity_id: switch.hall_light_spegel_switch
