alias: "Kör TV-läge då Apple TV spelar efter solnedgång"
trigger:
  platform: state
  entity_id: media_player.apple_tv
  to: 'playing'

condition:
  condition: and
  conditions:
    - condition: sun
      after: sunset
      after_offset: "-01:00:00"

action:
  service: input_select.select_option
  data:
    entity_id: input_select.scenepicker
    option: "TV"
