# Run evening script at sunset if someone is home
alias: "Scen Hemma vid solnedgång"
trigger:
  platform: sun
  event: sunset
  offset: '-00:00:15'

condition:
  condition: and
  conditions:
    - condition: state
      entity_id: group.all_devices
      state: 'home'

action:
  - service: input_select.select_option
    data:
      entity_id: input_select.scenepicker
      option: "Hemma"
